---
title: "Modeling"
author: "Cam Smithers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Necessary Packages

```{r}
library(tidyverse)
library(rsample)
library(caret)
library(vip)
library(ROCR)
```

Necessary Data Sets

```{r}
source("/Users/camsmithers/Desktop/Camalytics/NBA/inR/Functions.R")

team_season_stats <- readRDS(
    "/Users/camsmithers/Desktop/Camalytics/NBA/Data-NBA/team_season_stats.rds")

player_regseason_stats <- readRDS(
    "/Users/camsmithers/Desktop/Camalytics/NBA/Data-NBA/plyr_regsn_stats.rds")

team_box_scores <- readRDS(
    "/Users/camsmithers/Desktop/Camalytics/NBA/Data-NBA/team_box_scores_updated.rds")
```

```{r}
team_box_scores_2 <- team_box_scores %>%
    mutate(
        true_oreb_pct = round((oreb_pct * treb_pct) / 100, 1),
        true_dreb_pct = round((dreb_pct * treb_pct) / 100, 1))

opp_box_data <- team_box_scores %>%
    select(gamedate, team, pts, fg_pct, threefg_pct, efg_pct) %>%
    rename_with( ~paste0("opp_", .x), .cols = -c("gamedate", "team"))

team_box_scores_3 <- team_box_scores_2 %>%
    left_join(opp_box_data, by = c("gamedate", "opponent"="team")) %>%
    mutate(
        win = if_else(offrating > defrating, 1, 0),
        point_diff = pts - opp_pts,
        outcome_margin = case_when(
            point_diff >= 10 ~ 0,
            point_diff < 10 & point_diff > 0 ~ 1,
            point_diff < 0 & point_diff > -10 ~ 2,
            point_diff <= -10 ~ 3),
        win = factor(win,
                     levels = c(0, 1),
                     labels = c("Loss", "Win")),
        outcome_margin = factor(outcome_margin,
                                levels = c(0, 1, 2, 3),
                                labels = c("Blowout Win",
                                           "Close Win",
                                           "Close Loss",
                                           "Blowout Loss")))
```

```{r}

```
