---
title: "Exploration"
author: "Cam Smithers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
set.seed(123)
```

```{r}
source("/Users/camsmithers/Desktop/Camalytics/NBA/Functions.R")

team_box_scores <- readRDS(
    "/Users/camsmithers/Desktop/Camalytics/NBA/Data-NBA/team_box_scores.rds")

team_season_stats <- readRDS(
    "/Users/camsmithers/Desktop/Camalytics/NBA/Data-NBA/team_season_stats.rds")

player_box_scores <- readRDS(
    "/Users/camsmithers/Desktop/Camalytics/NBA/Data-NBA/full_box_player.rds")

player_season_stats <- readRDS(
    "/Users/camsmithers/Desktop/Camalytics/NBA/Data-NBA/player_season_stats.rds")
```

## Missing Player Relation to Outcome

### Finding the Most Important Player on Each Team

```{r}
find_best_player <- player_season_stats %>%
    select(year, team, name, pts, player_effrtg, vorp, box_plusminus, usage_rate, 
           on_off_net_per100poss, minutes) %>%
    rename("per" = "player_effrtg", "usage" = "usage_rate")

find_best_player_2 <- fixplayername(find_best_player)
```

```{r}
best_player_by_per <- best_player_metric(dataset = find_best_player_2, 
                                    main_col = per, 
                                    x = 24, y = 10)
best_player_by_vorp <- best_player_metric(dataset = find_best_player_2, 
                                          main_col = vorp,
                                           x = 24, y = 10)
best_player_by_usage <- best_player_metric(dataset = find_best_player_2, 
                                           main_col = usage,
                                           x = 24, y = 10)
```

```{r}
find_best_player_list <- list(best_player_by_per, 
                                best_player_by_vorp, 
                                best_player_by_usage)

find_best_player_2 <- reduce(find_best_player_list, 
                             full_join, 
                             by = c("team", "year", "name"))
```

```{r}
find_best_player_3 <- find_best_player_2 %>%
    select(-c(per, vorp, usage)) %>%
    mutate(
        year = as.numeric(year),
        best_by_metric = case_when(
            !is.na(per_player_id) & !is.na(vorp_player_id) & !is.na(usage_player_id) ~ 1,
            !is.na(usage_player_id) & !is.na(vorp_player_id) ~ 2,
            !is.na(per_player_id) & !is.na(usage_player_id) ~ 3,
            !is.na(per_player_id) & !is.na(vorp_player_id) ~ 4,
            !is.na(usage_player_id) ~ 5,
            !is.na(vorp_player_id) ~ 6,
            !is.na(per_player_id) ~ 7,
            TRUE ~ 8
        ))
```

```{r}
bp_usage_active <- bp_on_court(team_box_scores,
            player_box_scores, 
            best_player_by_usage,
            filter_by_col = min,
            best_by_id = usage_player_id)
```

```{r}
ggplot(bp_usage_active, 
       aes(x = win,
           fill = as.factor(best_by_player_avi))) +
    geom_bar(position = "dodge", color = "black") + 
    geom_text(stat = "count",
              aes(label = after_stat(count)),
              position = position_dodge(width = .9),
              vjust = -.5) +
    facet_wrap(~team) +
    labs(
        title = "Best Player Effect on Wins",
        fill = "Best Player Played"
    )
```

```{r}
test_model_empty <- glm(win ~ 1,
                        data = bp_usage_active, family = "binomial")
test_model_metric <- glm(win ~ best_by_player_avi
                         + team * season,
                         data = bp_usage_active, family = "binomial")
summary(test_model_empty)
summary(test_model_metric)
```

## Winning Team Characteristics

## Player Performance Variance During Season

## More Effective Play-Styles

## Most Common Combination
